const STORAGE_KEY = 'lifeos_language';

const PAGE_TEXT = {
    ar: { 'Good morning,': 'صباح الخير،', 'Progress': 'التقدم', "Today's Tasks": 'مهام اليوم', 'done': 'مكتملة', 'Done': 'مكتمل', 'Open': 'مفتوح', 'Upcoming Events': 'الأحداث القادمة', 'total': 'إجمالي', 'No location': 'لا يوجد موقع', 'TBD': 'يحدد لاحقاً', 'No upcoming events yet.': 'لا توجد أحداث قادمة بعد.', 'Smart Life Insights': 'رؤى الحياة الذكية', 'Checklist completion': 'إكمال قائمة المهام', 'Shopping focus': 'تركيز التسوق', 'pending': 'معلّق', 'Financial goal': 'الهدف المالي', 'Task Management': 'إدارة المهام', 'Add Task': 'إضافة مهمة', 'Smart Shopping List': 'قائمة تسوق ذكية', 'History': 'السجل', 'Add Item': 'إضافة عنصر', 'Estimated Pending Total:': 'الإجمالي المقدر للمعلّق:', 'Total Spent:': 'إجمالي الإنفاق:', 'Personal Goals & Milestones': 'الأهداف والمعالم الشخصية', 'Completed': 'مكتمل', 'Add Goal': 'إضافة هدف', 'Personal Notes': 'ملاحظات شخصية', 'Add Note': 'إضافة ملاحظة', 'Calendar & Appointments': 'التقويم والمواعيد', 'Add Event': 'إضافة حدث', 'Today': 'اليوم', 'Health & Wellness': 'الصحة والعافية', 'Family Organization': 'تنظيم العائلة', 'Add Member': 'إضافة عضو', 'Household Management': 'إدارة المنزل', 'Money Management': 'إدارة المال', 'Travel Planner': 'مخطط السفر', 'LifeOS AI Assistant': 'مساعد LifeOS الذكي' },
    fr: { 'Progress': 'Progression', "Today's Tasks": 'Tâches du jour', 'done': 'terminées', 'Done': 'Terminé', 'Open': 'Ouvert', 'Upcoming Events': 'Événements à venir', 'total': 'au total', 'No location': 'Aucun lieu', 'TBD': 'À définir', 'No upcoming events yet.': 'Aucun événement à venir.', 'Smart Life Insights': 'Aperçus LifeOS', 'Checklist completion': 'Achèvement de la liste', 'Shopping focus': 'Achats en cours', 'pending': 'en attente', 'Financial goal': 'Objectif financier', 'Task Management': 'Gestion des tâches', 'Add Task': 'Ajouter une tâche', 'Smart Shopping List': 'Liste de courses intelligente', 'History': 'Historique', 'Add Item': 'Ajouter un article', 'Estimated Pending Total:': 'Total estimé en attente :', 'Total Spent:': 'Total dépensé :', 'Personal Goals & Milestones': 'Objectifs et étapes', 'Completed': 'Terminé', 'Add Goal': 'Ajouter un objectif', 'Personal Notes': 'Notes personnelles', 'Add Note': 'Ajouter une note', 'Calendar & Appointments': 'Calendrier et rendez-vous', 'Add Event': 'Ajouter un événement', 'Today': "Aujourd'hui", 'Health & Wellness': 'Santé et bien-être', 'Family Organization': 'Organisation familiale', 'Add Member': 'Ajouter un membre', 'Household Management': 'Gestion du foyer', 'Money Management': 'Gestion financière', 'Travel Planner': 'Planificateur de voyage', 'LifeOS AI Assistant': 'Assistant IA LifeOS' },
    es: { 'Progress': 'Progreso', "Today's Tasks": 'Tareas de hoy', 'done': 'completadas', 'Done': 'Completada', 'Open': 'Abierta', 'Upcoming Events': 'Próximos eventos', 'total': 'en total', 'No location': 'Sin ubicación', 'TBD': 'Por definir', 'No upcoming events yet.': 'Aún no hay eventos próximos.', 'Smart Life Insights': 'Información de LifeOS', 'Checklist completion': 'Finalización de lista', 'Shopping focus': 'Compras pendientes', 'pending': 'pendientes', 'Financial goal': 'Objetivo financiero', 'Task Management': 'Gestión de tareas', 'Add Task': 'Añadir tarea', 'Smart Shopping List': 'Lista de compras inteligente', 'History': 'Historial', 'Add Item': 'Añadir artículo', 'Estimated Pending Total:': 'Total pendiente estimado:', 'Total Spent:': 'Total gastado:', 'Personal Goals & Milestones': 'Metas e hitos personales', 'Completed': 'Completadas', 'Add Goal': 'Añadir meta', 'Personal Notes': 'Notas personales', 'Add Note': 'Añadir nota', 'Calendar & Appointments': 'Calendario y citas', 'Add Event': 'Añadir evento', 'Today': 'Hoy', 'Health & Wellness': 'Salud y bienestar', 'Family Organization': 'Organización familiar', 'Add Member': 'Añadir miembro', 'Household Management': 'Gestión del hogar', 'Money Management': 'Gestión financiera', 'Travel Planner': 'Planificador de viajes', 'LifeOS AI Assistant': 'Asistente de IA LifeOS' },
    de: { 'Progress': 'Fortschritt', "Today's Tasks": 'Heutige Aufgaben', 'done': 'erledigt', 'Done': 'Erledigt', 'Open': 'Offen', 'Upcoming Events': 'Kommende Termine', 'total': 'insgesamt', 'No location': 'Kein Ort', 'TBD': 'Offen', 'No upcoming events yet.': 'Noch keine kommenden Termine.', 'Smart Life Insights': 'LifeOS-Einblicke', 'Checklist completion': 'Listenfortschritt', 'Shopping focus': 'Einkaufsfokus', 'pending': 'ausstehend', 'Financial goal': 'Finanzziel', 'Task Management': 'Aufgabenverwaltung', 'Add Task': 'Aufgabe hinzufügen', 'Smart Shopping List': 'Intelligente Einkaufsliste', 'History': 'Verlauf', 'Add Item': 'Artikel hinzufügen', 'Estimated Pending Total:': 'Geschätzte offene Summe:', 'Total Spent:': 'Gesamtausgaben:', 'Personal Goals & Milestones': 'Persönliche Ziele und Meilensteine', 'Completed': 'Abgeschlossen', 'Add Goal': 'Ziel hinzufügen', 'Personal Notes': 'Persönliche Notizen', 'Add Note': 'Notiz hinzufügen', 'Calendar & Appointments': 'Kalender und Termine', 'Add Event': 'Termin hinzufügen', 'Today': 'Heute', 'Health & Wellness': 'Gesundheit und Wohlbefinden', 'Family Organization': 'Familienorganisation', 'Add Member': 'Mitglied hinzufügen', 'Household Management': 'Haushaltsverwaltung', 'Money Management': 'Finanzverwaltung', 'Travel Planner': 'Reiseplaner', 'LifeOS AI Assistant': 'LifeOS KI-Assistent' },
    nl: { 'Progress': 'Voortgang', "Today's Tasks": 'Taken van vandaag', 'done': 'voltooid', 'Done': 'Klaar', 'Open': 'Open', 'Upcoming Events': 'Aankomende afspraken', 'total': 'totaal', 'No location': 'Geen locatie', 'TBD': 'Nog te bepalen', 'No upcoming events yet.': 'Nog geen aankomende afspraken.', 'Smart Life Insights': 'LifeOS-inzichten', 'Checklist completion': 'Checklist voltooiing', 'Shopping focus': 'Winkelfocus', 'pending': 'in afwachting', 'Financial goal': 'Financieel doel', 'Task Management': 'Taakbeheer', 'Add Task': 'Taak toevoegen', 'Smart Shopping List': 'Slimme boodschappenlijst', 'History': 'Geschiedenis', 'Add Item': 'Item toevoegen', 'Estimated Pending Total:': 'Geschat openstaand totaal:', 'Total Spent:': 'Totaal uitgegeven:', 'Personal Goals & Milestones': 'Persoonlijke doelen en mijlpalen', 'Completed': 'Voltooid', 'Add Goal': 'Doel toevoegen', 'Personal Notes': 'Persoonlijke notities', 'Add Note': 'Notitie toevoegen', 'Calendar & Appointments': 'Agenda en afspraken', 'Add Event': 'Afspraak toevoegen', 'Today': 'Vandaag', 'Health & Wellness': 'Gezondheid en welzijn', 'Family Organization': 'Gezinsorganisatie', 'Add Member': 'Lid toevoegen', 'Household Management': 'Huishoudbeheer', 'Money Management': 'Geldbeheer', 'Travel Planner': 'Reisplanner', 'LifeOS AI Assistant': 'LifeOS AI-assistent' },
    zh: { 'Progress': '进度', "Today's Tasks": '今日任务', 'done': '已完成', 'Done': '已完成', 'Open': '未完成', 'Upcoming Events': '即将到来的活动', 'total': '总计', 'No location': '未设置地点', 'TBD': '待定', 'No upcoming events yet.': '暂时没有即将到来的活动。', 'Smart Life Insights': 'LifeOS 洞察', 'Checklist completion': '任务清单完成度', 'Shopping focus': '购物待办', 'pending': '待处理', 'Financial goal': '财务目标', 'Task Management': '任务管理', 'Add Task': '添加任务', 'Smart Shopping List': '智能购物清单', 'History': '历史记录', 'Add Item': '添加项目', 'Estimated Pending Total:': '预计待付款总额：', 'Total Spent:': '总支出：', 'Personal Goals & Milestones': '个人目标与里程碑', 'Completed': '已完成', 'Add Goal': '添加目标', 'Personal Notes': '个人笔记', 'Add Note': '添加笔记', 'Calendar & Appointments': '日历和预约', 'Add Event': '添加活动', 'Today': '今天', 'Health & Wellness': '健康与身心', 'Family Organization': '家庭组织', 'Add Member': '添加成员', 'Household Management': '家庭管理', 'Money Management': '财务管理', 'Travel Planner': '旅行计划', 'LifeOS AI Assistant': 'LifeOS AI 助手' },
    ja: { 'Progress': '進捗', "Today's Tasks": '今日のタスク', 'done': '完了', 'Done': '完了', 'Open': '未完了', 'Upcoming Events': '今後の予定', 'total': '合計', 'No location': '場所なし', 'TBD': '未定', 'No upcoming events yet.': '今後の予定はありません。', 'Smart Life Insights': 'LifeOS インサイト', 'Checklist completion': 'チェックリストの完了率', 'Shopping focus': '買い物の予定', 'pending': '保留中', 'Financial goal': '資金目標', 'Task Management': 'タスク管理', 'Add Task': 'タスクを追加', 'Smart Shopping List': 'スマート買い物リスト', 'History': '履歴', 'Add Item': '項目を追加', 'Estimated Pending Total:': '予定支出合計:', 'Total Spent:': '支出合計:', 'Personal Goals & Milestones': '個人目標とマイルストーン', 'Completed': '完了', 'Add Goal': '目標を追加', 'Personal Notes': '個人メモ', 'Add Note': 'メモを追加', 'Calendar & Appointments': 'カレンダーと予定', 'Add Event': '予定を追加', 'Today': '今日', 'Health & Wellness': '健康とウェルネス', 'Family Organization': '家族管理', 'Add Member': 'メンバーを追加', 'Household Management': '家庭管理', 'Money Management': '家計管理', 'Travel Planner': '旅行プランナー', 'LifeOS AI Assistant': 'LifeOS AI アシスタント' }
};

export const LANGUAGES = {
    en: { name: 'English', dir: 'ltr', labels: { dashboard: 'Dashboard', calendar: 'Calendar', tasks: 'Tasks', shopping: 'Shopping', money: 'Money', home: 'Home', family: 'Family', goals: 'Goals', notes: 'Notes', social: 'Social Hub', ai: 'AI Assistant', currency: 'Currency', accent: 'Accent Color', darkMode: 'Dark Mode', lightMode: 'Light Mode', search: 'Search LifeOS across tasks, events, notes, goals...', welcomeKicker: 'Your personal life operating system', welcomeTitle: 'Bring your days into focus.', welcomeCopy: 'Organize tasks, money, goals, notes, family, and the moments that matter in one calm workspace.', create: 'Create an Account', signIn: 'Sign In', welcome: 'Welcome to LifeOS', name: 'Full name', email: 'Email address', password: 'Password', address: 'Address', country: 'Country', phone: 'Telephone number', close: 'Close', save: 'Save', createAccount: 'Create Account' } },
        en: { name: 'English', dir: 'ltr', labels: { language: 'Language', dashboard: 'Dashboard', calendar: 'Calendar', tasks: 'Tasks', shopping: 'Shopping', money: 'Money', home: 'Home', family: 'Family', goals: 'Goals', notes: 'Notes', social: 'Social Hub', ai: 'AI Assistant', currency: 'Currency', accent: 'Accent Color', darkMode: 'Dark Mode', lightMode: 'Light Mode', search: 'Search LifeOS across tasks, events, notes, goals...', welcomeKicker: 'Your personal life operating system', welcomeTitle: 'Bring your days into focus.', welcomeCopy: 'Organize tasks, money, goals, notes, family, and the moments that matter in one calm workspace.', create: 'Create an Account', signIn: 'Sign In', welcome: 'Welcome to LifeOS', name: 'Full name', email: 'Email address', password: 'Password', address: 'Address', country: 'Country', phone: 'Telephone number', close: 'Close', save: 'Save', createAccount: 'Create Account' } },
    ar: { name: 'العربية', dir: 'rtl', labels: { dashboard: 'لوحة التحكم', calendar: 'التقويم', tasks: 'المهام', shopping: 'التسوق', money: 'المال', home: 'المنزل', family: 'العائلة', goals: 'الأهداف', notes: 'الملاحظات', social: 'التواصل الاجتماعي', ai: 'المساعد الذكي', currency: 'العملة', accent: 'لون التمييز', darkMode: 'الوضع الداكن', lightMode: 'الوضع الفاتح', search: 'ابحث في LifeOS عن المهام والأحداث والملاحظات والأهداف...', welcomeKicker: 'نظامك الشخصي لإدارة الحياة', welcomeTitle: 'رتّب أيامك بوضوح.', welcomeCopy: 'نظّم مهامك وأموالك وأهدافك وملاحظاتك وعائلتك في مساحة واحدة.', create: 'إنشاء حساب', signIn: 'تسجيل الدخول', welcome: 'مرحباً بك في LifeOS', name: 'الاسم الكامل', email: 'البريد الإلكتروني', password: 'كلمة المرور', address: 'العنوان', country: 'الدولة', phone: 'رقم الهاتف', close: 'إغلاق', save: 'حفظ', createAccount: 'إنشاء حساب' } },
    fr: { name: 'Français', dir: 'ltr', labels: { dashboard: 'Tableau de bord', calendar: 'Calendrier', tasks: 'Tâches', shopping: 'Achats', money: 'Finances', home: 'Maison', family: 'Famille', goals: 'Objectifs', notes: 'Notes', social: 'Réseaux sociaux', ai: 'Assistant IA', currency: 'Devise', accent: 'Couleur d’accent', darkMode: 'Mode sombre', lightMode: 'Mode clair', search: 'Rechercher dans LifeOS...', welcomeKicker: 'Votre système personnel de vie', welcomeTitle: 'Donnez du sens à vos journées.', welcomeCopy: 'Organisez vos tâches, finances, objectifs, notes et famille au même endroit.', create: 'Créer un compte', signIn: 'Se connecter', welcome: 'Bienvenue sur LifeOS', name: 'Nom complet', email: 'Adresse e-mail', password: 'Mot de passe', address: 'Adresse', country: 'Pays', phone: 'Téléphone', close: 'Fermer', save: 'Enregistrer', createAccount: 'Créer un compte' } },
    es: { name: 'Español', dir: 'ltr', labels: { dashboard: 'Panel', calendar: 'Calendario', tasks: 'Tareas', shopping: 'Compras', money: 'Finanzas', home: 'Hogar', family: 'Familia', goals: 'Objetivos', notes: 'Notas', social: 'Redes sociales', ai: 'Asistente IA', currency: 'Moneda', accent: 'Color de acento', darkMode: 'Modo oscuro', lightMode: 'Modo claro', search: 'Buscar en LifeOS...', welcomeKicker: 'Tu sistema personal de vida', welcomeTitle: 'Enfoca tus días.', welcomeCopy: 'Organiza tus tareas, finanzas, objetivos, notas y familia en un solo lugar.', create: 'Crear cuenta', signIn: 'Iniciar sesión', welcome: 'Bienvenido a LifeOS', name: 'Nombre completo', email: 'Correo electrónico', password: 'Contraseña', address: 'Dirección', country: 'País', phone: 'Teléfono', close: 'Cerrar', save: 'Guardar', createAccount: 'Crear cuenta' } },
    de: { name: 'Deutsch', dir: 'ltr', labels: { dashboard: 'Übersicht', calendar: 'Kalender', tasks: 'Aufgaben', shopping: 'Einkaufen', money: 'Finanzen', home: 'Haushalt', family: 'Familie', goals: 'Ziele', notes: 'Notizen', social: 'Soziale Medien', ai: 'KI-Assistent', currency: 'Währung', accent: 'Akzentfarbe', darkMode: 'Dunkelmodus', lightMode: 'Hellmodus', search: 'LifeOS durchsuchen...', welcomeKicker: 'Dein persönliches Lebenssystem', welcomeTitle: 'Bringe deine Tage in den Fokus.', welcomeCopy: 'Organisiere Aufgaben, Finanzen, Ziele, Notizen und Familie an einem Ort.', create: 'Konto erstellen', signIn: 'Anmelden', welcome: 'Willkommen bei LifeOS', name: 'Vollständiger Name', email: 'E-Mail-Adresse', password: 'Passwort', address: 'Adresse', country: 'Land', phone: 'Telefonnummer', close: 'Schließen', save: 'Speichern', createAccount: 'Konto erstellen' } },
    nl: { name: 'Nederlands', dir: 'ltr', labels: { dashboard: 'Dashboard', calendar: 'Agenda', tasks: 'Taken', shopping: 'Boodschappen', money: 'Financiën', home: 'Huis', family: 'Familie', goals: 'Doelen', notes: 'Notities', social: 'Sociale media', ai: 'AI-assistent', currency: 'Valuta', accent: 'Accentkleur', darkMode: 'Donkere modus', lightMode: 'Lichte modus', search: 'Zoek in LifeOS...', welcomeKicker: 'Jouw persoonlijke levenssysteem', welcomeTitle: 'Breng je dagen in focus.', welcomeCopy: 'Organiseer taken, geld, doelen, notities en familie op één plek.', create: 'Account maken', signIn: 'Inloggen', welcome: 'Welkom bij LifeOS', name: 'Volledige naam', email: 'E-mailadres', password: 'Wachtwoord', address: 'Adres', country: 'Land', phone: 'Telefoonnummer', close: 'Sluiten', save: 'Opslaan', createAccount: 'Account maken' } },
    zh: { name: '中文', dir: 'ltr', labels: { dashboard: '仪表盘', calendar: '日历', tasks: '任务', shopping: '购物', money: '财务', home: '家庭', family: '家人', goals: '目标', notes: '笔记', social: '社交中心', ai: 'AI 助手', currency: '货币', accent: '主题颜色', darkMode: '深色模式', lightMode: '浅色模式', search: '搜索 LifeOS...', welcomeKicker: '你的个人生活操作系统', welcomeTitle: '让每一天更专注。', welcomeCopy: '在一个空间管理任务、财务、目标、笔记和家人。', create: '创建账户', signIn: '登录', welcome: '欢迎使用 LifeOS', name: '姓名', email: '电子邮箱', password: '密码', address: '地址', country: '国家', phone: '电话号码', close: '关闭', save: '保存', createAccount: '创建账户' } },
    ja: { name: '日本語', dir: 'ltr', labels: { dashboard: 'ダッシュボード', calendar: 'カレンダー', tasks: 'タスク', shopping: '買い物', money: '家計', home: 'ホーム', family: '家族', goals: '目標', notes: 'メモ', social: 'ソーシャル', ai: 'AIアシスタント', currency: '通貨', accent: 'アクセントカラー', darkMode: 'ダークモード', lightMode: 'ライトモード', search: 'LifeOSを検索...', welcomeKicker: 'あなたの生活オペレーティングシステム', welcomeTitle: '毎日に集中しましょう。', welcomeCopy: 'タスク、家計、目標、メモ、家族を一つの場所で管理できます。', create: 'アカウント作成', signIn: 'ログイン', welcome: 'LifeOSへようこそ', name: '氏名', email: 'メールアドレス', password: 'パスワード', address: '住所', country: '国', phone: '電話番号', close: '閉じる', save: '保存', createAccount: 'アカウント作成' } },
};

export function getLanguage() { return localStorage.getItem(STORAGE_KEY) || 'en'; }
export function t(key) { return LANGUAGES[getLanguage()]?.labels[key] || LANGUAGES.en.labels[key] || key; }
export function applyLanguage(language, notify = true) {
    const key = LANGUAGES[language] ? language : 'en';
    localStorage.setItem(STORAGE_KEY, key);
    document.documentElement.lang = key;
    document.documentElement.dir = LANGUAGES[key].dir;
    document.documentElement.dataset.language = key;
    document.querySelectorAll('[data-i18n]').forEach(element => { element.textContent = t(element.dataset.i18n); });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(element => { element.placeholder = t(element.dataset.i18nPlaceholder); });
    if (notify) window.dispatchEvent(new Event('lifeos:language-changed'));
    return key;
}

export function localizePageContent(container) {
    const translations = PAGE_TEXT[getLanguage()] || {};
    const walker = document.createTreeWalker(container, NodeFilter.SHOW_TEXT);
    const textNodes = [];
    let node;
    while ((node = walker.nextNode())) textNodes.push(node);
    textNodes.forEach(textNode => {
        const original = textNode.nodeValue;
        const trimmed = original.trim();
        const translated = translations[trimmed];
        if (translated) textNode.nodeValue = original.replace(trimmed, translated);
    });
}
export function initLanguageSelector() {
    const select = document.getElementById('language-select');
    if (!select) return;
    select.innerHTML = Object.entries(LANGUAGES).map(([key, language]) => `<option value="${key}">${language.name}</option>`).join('');
    select.value = getLanguage();
    select.onchange = () => { applyLanguage(select.value); };
    applyLanguage(select.value, false);
}
